jikkyotter/urls.py
from django.urls import path
from . import views


app_name = 'jikkyotter'

urlpatterns = [
    path('', views.PostList.as_view(), name='index'),
    path('post/create/', views.CreatePost.as_view(), name='post_create'),
    path('post/detail/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('user/detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user/<int:pk>/posts/', views.UserPostList.as_view(), name='user_posts'),
    path('about/', views.AboutView.as_view(), name='about'),
]

jikkyou_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jikkyotter.urls')),
    path('accounts/', include('allauth.urls')),
]

jikkyotter/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from taggit.managers import TaggableManager


class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta(AbstractUser.Meta):
        db_table = 'customuser'

    created_at = models.DateTimeField('登録日時', default=timezone.now)

    def __self__(self):
        return self.username


class Post(models.Model):
    """投稿モデル"""
    class Meta:
        db_table = 'post'

    title = models.CharField('タイトル', max_length=140)
    start_at = models.DateTimeField('開始日時')
    created_at = models.DateTimeField('作成日時', default=timezone.now)
    comment = models.TextField('コメント', max_length=140, null=True, blank=True)
    tags = TaggableManager(blank=True)
    user = models.ForeignKey(CustomUser, verbose_name='投稿', on_delete=models.PROTECT)

    def __str__(self):
        return self.title

jikkyotter/forms.py
from django import forms
from .models import Post
import bootstrap_datepicker_plus as datetimepicker


class PostForm(forms.ModelForm):
    """新規投稿のモデルフォーム"""

    class Meta:
        model = Post
        fields = ('title', 'start_at', 'comment', 'tags')
        widgets = {
            'start_at': datetimepicker.DateTimePickerInput(
                format='%Y-%m-%d %H:%M:%S',
                attrs={'readonly': 'true'},
                options={
                    'locale': 'ja',
                    'dayViewHeaderFormat': 'YYYY年 MMMM',
                    'ignoreReadonly': True,
                    'allowInputToggle': True,
                }
            )
        }


class SearchForm(forms.Form):
    """検索フォーム"""
    keyword = forms.CharField(label='キーワード', max_length=100, required=False)
    tag = forms.CharField(label='タグ', max_length=100, required=False)

jikkyotter/views.py
from django.views import generic
from . import models
from . import forms
from jikkyotter import manage_twitter
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class PostList(generic.ListView):
    """トップページのビュー。投稿一覧のような感じ"""
    model = models.Post
    context_object_name = 'posts'
    paginate_by = 5
    ordering = ['-start_at']

    def get_context_data(self, *, object_list=models.Post, **kwargs):
        """SearchFormをテンプレートに渡す"""
        context = super().get_context_data()
        context['form'] = forms.SearchForm(self.request.GET)
        return context

    def get_queryset(self):
        """フォームを利用してPostを検索"""
        form = forms.SearchForm(self.request.GET)
        form.is_valid()

        queryset = super().get_queryset()
        keyword = form.cleaned_data['keyword']
        if keyword:
            queryset = queryset.filter(Q(title__icontains=keyword) | Q(comment__icontains=keyword)
                                       | Q(tags__name__icontains=keyword)).distinct()
        tag = form.cleaned_data['tag']
        if tag:
            queryset = queryset.filter(tags__name=tag)
        return queryset


@method_decorator(login_required, name='dispatch')
class CreatePost(generic.CreateView):
    """新規投稿のビュー。ModelFormを使う"""
    form_class = forms.PostForm
    template_name = 'jikkyotter/create.html'
    success_url = '/'

    def form_valid(self, form):
        """Postを新規作成するときにuserカラムにデータを入れる"""
        post = form.save(commit=False)
        post.user = self.request.user
        return super(CreatePost, self).form_valid(form)


class PostDetail(generic.DetailView):
    """ 投稿詳細のビュー"""
    model = models.Post


class UserDetail(generic.DetailView):
    """ユーザー詳細のビュー"""
    model = models.CustomUser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['twitter_user'] = manage_twitter.get_twitter_user_info(self.kwargs['pk'])
        context['posts'] = models.Post.objects.filter(user__pk=self.kwargs['pk'])[:5]
        context['twitter_icon'] = manage_twitter.get_twitter_bigger_icon(self.kwargs['pk'])
        return context


class UserPostList(generic.ListView):
    model = models.Post
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'jikkyotter/user_post_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user__pk=self.kwargs['pk'])
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['twitter_user'] = manage_twitter.get_twitter_user_info(self.kwargs['pk'])
        return context


class AboutView(generic.TemplateView):
    template_name = 'jikkyotter/about.html'

templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {% block extrahead %}
    {% endblock %}

    <title>実況ったー</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'jikkyotter:index' %}">実況ったー</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'jikkyotter:about' %}">実況ったーとは</a></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'jikkyotter:post_create' %}">新規作成</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">ログイン</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container pt-5 col-md-6">
      {% bootstrap_messages %}
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/jikkyotter/about.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div class="text-center">
    <h2>実況ったーとは？</h2>
    <p>Twitterリアタイ実況できない人向けに、NetflixやらAmazon Prime Videoやらでタイミング合わせて
      一緒にアニメ（など）見ようぜ！っていうサービスです。</p>
    <p>Twitter実況すると盛り上がるし、一緒に見てる人と仲良くなれる気がしてよかったので作りました。</p>
  </div>
  <div class="text-center">
    <h2>使い方</h2>
    <ol>
      <li>ナビゲーションバーから「ログイン」をクリックして、Twitterアカウントを用いてサインアップしてください。</li>
      <li>ログインできたら、ナビゲーションバーから「新規作成」をクリックしてください。投稿のタイトル、コメント、実況開始時刻、タグを指定して投稿してください。</li>
      <li>投稿したら、その投稿詳細ページへ行き、ツイートボタンを押してください。ハッシュタグが自動生成され、詳細ページのリンクが載ったTwitter投稿画面が表示されます。</li>
      <li>開始時刻になったらそのハッシュタグを付けて、実況を始めましょう！</li>
    </ol>
    <p>Twitterのハッシュタグの仕様上、アンダーバー以外の記号でハッシュタグが途切れてしまうので省略することを推奨します。（例「ゆるキャン△」→「ゆるキャン」、「ダンベル何キロもてる？」→「ダンベル何キロもてる」など）</p>
  </div>
  <div class="text-center">
    <h2>運営者：とともね</h2>
    <p>よわよわ未経験エンジニアが運営していますので、優しい目で見てください</p>
    <p>ここ修正したほうがいいよとか、ここを直してほしいなど有りましたら、TwitterのDMでお願いします→<a href="https://twitter.com/ttmone_">Twitter</a></p>
  </div>
  </div>
{% endblock %}

templates/jikkyotter/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block content %}
  <div class="text-center">
    <h2>実況作成</h2>
    <form method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_form_errors form %}
      {% buttons %}
      <button type="submit" class="btn btn-primary">
        投稿
      </button>
      {% endbuttons %}
    </form>
  </div>
{% endblock %}

templates/jikkyotter/customuser_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">
  <h2>{{ twitter_user.name }}</h2>
  <h4>@{{ customuser.username }}</h4>
  <p><img src="{{ twitter_icon }}"></p>
</div>

<h3>最近の実況</h3>
{% include 'jikkyotter/snippets/post_card_list.html' %}

<button class="btn btn-info my-3" onclick="location.href='{% url 'jikkyotter:user_posts' pk=customuser.id %}'">投稿一覧</button>

{% endblock %}

templates/jikkyotter/post_detail.html
{% extends 'base.html' %}


{% block content %}
  <div class="text-center">
    <h2>{{ post.title }}</h2>
    <h4>{{ post.start_at }}</h4>
    <p>{{ post.comment }}</p>
    <p>by <a href="{% url 'jikkyotter:user_detail' pk=post.user.id %}">@{{ post.user }}</a></p>
    <div>
      {% for tag in post.tags.names %}
          <a href="{% url 'jikkyotter:index' %}?tag={{ tag }}">{{ tag }}</a>
      {% endfor %}
    </div>
    <a class="btn btn-primary mt-3" href="https://twitter.com/intent/tweet?url={{ request.scheme }}://{{ request.get_host }}{% url 'jikkyotter:post_detail' post.pk %}&text=%20%23{{ post.title }}%0a{{ post.comment|linebreaksbr }}%0a{{ post.start_at|date:"Y年m月j日H時i分" }}から" target="_blank">
    ツイート
    </a>
{#    <a class="btn btn-primary" href="https://twitter.com/intent/tweet?url={{ request.scheme }}://{{ request.get_host }}{% url 'app:detail' post.pk %}&text={{ post.comment }}&hashtags=いつでもエア実況_{{ post.title }}_{{ post.episode }}話_{{ post.start_time|date:"Y年m月j日H時i分" }}から" target="_blank">#}
  </div>
{% endblock %}

templates/jikkyotter/post_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<h2 class="text-center">投稿一覧</h2>
{% include 'jikkyotter/snippets/post_card_list.html' %}

{# ページネーション #}
{% include 'jikkyotter/snippets/page5.html' %}

<h2 class="text-center">検索フォーム</h2>
<form action="" method="GET">
  {% bootstrap_form form %}
  <div class="text-center">
    <button type="submit" class="btn btn-info mb-5">検索</button>
  </div>
</form>

{% endblock %}

templates/jikkyotter/snippets/page5.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination mt-3 justify-content-center">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>

templates/jikkyotter/snippets/post_card_list.html
{% for post in posts %}
<div class="card">
  <div class="card-body">
    <h4 class="card-title"><a href="{% url 'jikkyotter:post_detail' pk=post.id %}">{{ post.title }}</a></h4>
    <h6 class="card-subtitle mb-2 text-muted">{{ post.start_at }}</h6>
    <p class="card-text">
      {{ post.comment | truncatechars:40 }}
    </p>
    <a href="{% url 'jikkyotter:user_detail' pk=post.user.id %}">{{ post.user }}</a>
    <div>
      {% for tag in post.tags.names %}
          <a href="{% url 'jikkyotter:index' %}?tag={{ tag }}">{{ tag }}</a>
      {% endfor %}
    </div>
  </div>
</div>
{% endfor %}
{% if not posts %}
  <p>検索結果：なし</p>
{% endif %}

templates/jikkyotter/user_post_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h2>@{{ twitter_user.screen_name }}の投稿一覧</h2>
{% for post in posts %}
<div class="card">
  <div class="card-body">
    <h4 class="card-title"><a href="{% url 'jikkyotter:post_detail' pk=post.id %}">{{ post.title }}</a></h4>
    <h6 class="card-subtitle mb-2 text-muted">{{ post.start_at }}</h6>
    <p class="card-text">
      {{ post.comment }}
    </p><a href="{% url 'jikkyotter:user_detail' pk=post.user.id %}">{{ post.user }}</a>
    <div>
      {% for tag in post.tags.names %}
          <a href="{% url 'jikkyotter:index' %}?tag={{ tag }}">{{ tag }}</a>
      {% endfor %}
    </div>
  </div>
</div>
{% endfor %}

{# ページネーション #}
{% include 'jikkyotter/snippets/page5.html' %}

{% endblock %}